//
// Autogenerated by Thrift Compiler (0.22.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require("thrift");
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require("node-int64");

var ttypes = require("./inventory_types");
//HELPER FUNCTIONS AND STRUCTURES

var InventoryService_getStock_args = function (args) {
  this.sku = null;
  if (args) {
    if (args.sku !== undefined && args.sku !== null) {
      this.sku = args.sku;
    }
  }
};
InventoryService_getStock_args.prototype = {};
InventoryService_getStock_args.prototype[Symbol.for("read")] = function (
  input
) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    console.log(ret);
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
        if (ftype == Thrift.Type.STRING) {
          this.sku = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InventoryService_getStock_args.prototype[Symbol.for("write")] = function (
  output
) {
  output.writeStructBegin("InventoryService_getStock_args");
  if (this.sku !== null && this.sku !== undefined) {
    output.writeFieldBegin("sku", Thrift.Type.STRING, 1);
    output.writeString(this.sku);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InventoryService_getStock_result = function (args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.StockInfo(args.success);
    }
  }
};
InventoryService_getStock_result.prototype = {};
InventoryService_getStock_result.prototype[Symbol.for("read")] = function (
  input
) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
        if (ftype == Thrift.Type.STRUCT) {
          this.success = new ttypes.StockInfo();
          this.success[Symbol.for("read")](input);
        } else {
          input.skip(ftype);
        }
        break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InventoryService_getStock_result.prototype[Symbol.for("write")] = function (
  output
) {
  output.writeStructBegin("InventoryService_getStock_result");
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin("success", Thrift.Type.STRUCT, 0);
    this.success[Symbol.for("write")](output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InventoryService_deduct_args = function (args) {
  this.sku = null;
  this.quantity = null;
  if (args) {
    if (args.sku !== undefined && args.sku !== null) {
      this.sku = args.sku;
    }
    if (args.quantity !== undefined && args.quantity !== null) {
      this.quantity = args.quantity;
    }
  }
};
InventoryService_deduct_args.prototype = {};
InventoryService_deduct_args.prototype[Symbol.for("read")] = function (input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
        if (ftype == Thrift.Type.STRING) {
          this.sku = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
      case 2:
        if (ftype == Thrift.Type.I32) {
          this.quantity = input.readI32();
        } else {
          input.skip(ftype);
        }
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InventoryService_deduct_args.prototype[Symbol.for("write")] = function (
  output
) {
  output.writeStructBegin("InventoryService_deduct_args");
  if (this.sku !== null && this.sku !== undefined) {
    output.writeFieldBegin("sku", Thrift.Type.STRING, 1);
    output.writeString(this.sku);
    output.writeFieldEnd();
  }
  if (this.quantity !== null && this.quantity !== undefined) {
    output.writeFieldBegin("quantity", Thrift.Type.I32, 2);
    output.writeI32(this.quantity);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InventoryService_deduct_result = function (args) {
  this.success = null;
  this.insufficient = null;
  if (args instanceof ttypes.InsufficientStockException) {
    this.insufficient = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.DeductResult(args.success);
    }
    if (args.insufficient !== undefined && args.insufficient !== null) {
      this.insufficient = args.insufficient;
    }
  }
};
InventoryService_deduct_result.prototype = {};
InventoryService_deduct_result.prototype[Symbol.for("read")] = function (
  input
) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
        if (ftype == Thrift.Type.STRUCT) {
          this.success = new ttypes.DeductResult();
          this.success[Symbol.for("read")](input);
        } else {
          input.skip(ftype);
        }
        break;
      case 1:
        if (ftype == Thrift.Type.STRUCT) {
          this.insufficient = new ttypes.InsufficientStockException();
          this.insufficient[Symbol.for("read")](input);
        } else {
          input.skip(ftype);
        }
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InventoryService_deduct_result.prototype[Symbol.for("write")] = function (
  output
) {
  output.writeStructBegin("InventoryService_deduct_result");
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin("success", Thrift.Type.STRUCT, 0);
    this.success[Symbol.for("write")](output);
    output.writeFieldEnd();
  }
  if (this.insufficient !== null && this.insufficient !== undefined) {
    output.writeFieldBegin("insufficient", Thrift.Type.STRUCT, 1);
    this.insufficient[Symbol.for("write")](output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InventoryServiceClient = function (output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
InventoryServiceClient.prototype = {};
InventoryServiceClient.prototype.seqid = function () {
  return this._seqid;
};
InventoryServiceClient.prototype.new_seqid = function () {
  return (this._seqid += 1);
};

InventoryServiceClient.prototype.getStock = function (sku, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function (error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getStock(sku);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getStock(sku);
  }
};

InventoryServiceClient.prototype.send_getStock = function (sku) {
  var output = new this.pClass(this.output);
  var params = {
    sku: sku,
  };
  var args = new InventoryService_getStock_args(params);
  try {
    output.writeMessageBegin("getStock", Thrift.MessageType.CALL, this.seqid());
    args[Symbol.for("write")](output);
    output.writeMessageEnd();
    return this.output.flush();
  } catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === "function") {
      output.reset();
    }
    throw e;
  }
};

InventoryServiceClient.prototype.recv_getStock = function (
  input,
  mtype,
  rseqid
) {
  var callback = this._reqs[rseqid] || function () {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x[Symbol.for("read")](input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new InventoryService_getStock_result();
  result[Symbol.for("read")](input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback("getStock failed: unknown result");
};

InventoryServiceClient.prototype.deduct = function (sku, quantity, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function (error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_deduct(sku, quantity);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_deduct(sku, quantity);
  }
};

InventoryServiceClient.prototype.send_deduct = function (sku, quantity) {
  var output = new this.pClass(this.output);
  var params = {
    sku: sku,
    quantity: quantity,
  };
  var args = new InventoryService_deduct_args(params);
  try {
    output.writeMessageBegin("deduct", Thrift.MessageType.CALL, this.seqid());
    args[Symbol.for("write")](output);
    output.writeMessageEnd();
    return this.output.flush();
  } catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === "function") {
      output.reset();
    }
    throw e;
  }
};

InventoryServiceClient.prototype.recv_deduct = function (input, mtype, rseqid) {
  var callback = this._reqs[rseqid] || function () {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x[Symbol.for("read")](input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new InventoryService_deduct_result();
  result[Symbol.for("read")](input);
  input.readMessageEnd();

  if (null !== result.insufficient) {
    return callback(result.insufficient);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback("deduct failed: unknown result");
};
exports.Client = InventoryServiceClient;
var InventoryServiceProcessor = function (handler) {
  this._handler = handler;
};
InventoryServiceProcessor.prototype.process = function (input, output) {
  var r = input.readMessageBegin();
  if (this["process_" + r.fname]) {
    return this["process_" + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(
      Thrift.TApplicationExceptionType.UNKNOWN_METHOD,
      "Unknown function " + r.fname
    );
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x[Symbol.for("write")](output);
    output.writeMessageEnd();
    output.flush();
  }
};
InventoryServiceProcessor.prototype.process_getStock = function (
  seqid,
  input,
  output
) {
  var args = new InventoryService_getStock_args();
  args[Symbol.for("read")](input);
  input.readMessageEnd();
  if (this._handler.getStock.length === 1) {
    Q.fcall(this._handler.getStock.bind(this._handler), args.sku)
      .then(function (result) {
        var result_obj = new InventoryService_getStock_result({
          success: result,
        });
        output.writeMessageBegin("getStock", Thrift.MessageType.REPLY, seqid);
        result_obj[Symbol.for("write")](output);
        output.writeMessageEnd();
        output.flush();
      })
      .catch(function (err) {
        var result;
        result = new Thrift.TApplicationException(
          Thrift.TApplicationExceptionType.UNKNOWN,
          err.message
        );
        output.writeMessageBegin(
          "getStock",
          Thrift.MessageType.EXCEPTION,
          seqid
        );
        result[Symbol.for("write")](output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getStock(args.sku, function (err, result) {
      var result_obj;
      if (err === null || typeof err === "undefined") {
        result_obj = new InventoryService_getStock_result(
          err !== null || typeof err === "undefined" ? err : { success: result }
        );
        output.writeMessageBegin("getStock", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(
          Thrift.TApplicationExceptionType.UNKNOWN,
          err.message
        );
        output.writeMessageBegin(
          "getStock",
          Thrift.MessageType.EXCEPTION,
          seqid
        );
      }
      result_obj[Symbol.for("write")](output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
InventoryServiceProcessor.prototype.process_deduct = function (
  seqid,
  input,
  output
) {
  var args = new InventoryService_deduct_args();
  args[Symbol.for("read")](input);
  input.readMessageEnd();
  if (this._handler.deduct.length === 2) {
    Q.fcall(this._handler.deduct.bind(this._handler), args.sku, args.quantity)
      .then(function (result) {
        var result_obj = new InventoryService_deduct_result({
          success: result,
        });
        output.writeMessageBegin("deduct", Thrift.MessageType.REPLY, seqid);
        result_obj[Symbol.for("write")](output);
        output.writeMessageEnd();
        output.flush();
      })
      .catch(function (err) {
        var result;
        if (err instanceof ttypes.InsufficientStockException) {
          result = new InventoryService_deduct_result(err);
          output.writeMessageBegin("deduct", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(
            Thrift.TApplicationExceptionType.UNKNOWN,
            err.message
          );
          output.writeMessageBegin(
            "deduct",
            Thrift.MessageType.EXCEPTION,
            seqid
          );
        }
        result[Symbol.for("write")](output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.deduct(args.sku, args.quantity, function (err, result) {
      var result_obj;
      if (
        err === null ||
        typeof err === "undefined" ||
        err instanceof ttypes.InsufficientStockException
      ) {
        result_obj = new InventoryService_deduct_result(
          err !== null || typeof err === "undefined" ? err : { success: result }
        );
        output.writeMessageBegin("deduct", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(
          Thrift.TApplicationExceptionType.UNKNOWN,
          err.message
        );
        output.writeMessageBegin("deduct", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj[Symbol.for("write")](output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
exports.Processor = InventoryServiceProcessor;
