//
// Autogenerated by Thrift Compiler (0.22.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = module.exports = {};
var StockInfo = module.exports.StockInfo = function(args) {
  this.sku = null;
  this.stock = null;
  if (args) {
    if (args.sku !== undefined && args.sku !== null) {
      this.sku = args.sku;
    }
    if (args.stock !== undefined && args.stock !== null) {
      this.stock = args.stock;
    }
  }
};
StockInfo.prototype = {};
StockInfo.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.sku = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.stock = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StockInfo.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('StockInfo');
  if (this.sku !== null && this.sku !== undefined) {
    output.writeFieldBegin('sku', Thrift.Type.STRING, 1);
    output.writeString(this.sku);
    output.writeFieldEnd();
  }
  if (this.stock !== null && this.stock !== undefined) {
    output.writeFieldBegin('stock', Thrift.Type.I32, 2);
    output.writeI32(this.stock);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DeductResult = module.exports.DeductResult = function(args) {
  this.sku = null;
  this.deducted = null;
  this.stock = null;
  if (args) {
    if (args.sku !== undefined && args.sku !== null) {
      this.sku = args.sku;
    }
    if (args.deducted !== undefined && args.deducted !== null) {
      this.deducted = args.deducted;
    }
    if (args.stock !== undefined && args.stock !== null) {
      this.stock = args.stock;
    }
  }
};
DeductResult.prototype = {};
DeductResult.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.sku = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.deducted = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.stock = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DeductResult.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('DeductResult');
  if (this.sku !== null && this.sku !== undefined) {
    output.writeFieldBegin('sku', Thrift.Type.STRING, 1);
    output.writeString(this.sku);
    output.writeFieldEnd();
  }
  if (this.deducted !== null && this.deducted !== undefined) {
    output.writeFieldBegin('deducted', Thrift.Type.I32, 2);
    output.writeI32(this.deducted);
    output.writeFieldEnd();
  }
  if (this.stock !== null && this.stock !== undefined) {
    output.writeFieldBegin('stock', Thrift.Type.I32, 3);
    output.writeI32(this.stock);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InsufficientStockException = module.exports.InsufficientStockException = function(args) {
  Thrift.TException.call(this, "InsufficientStockException");
  this.name = "InsufficientStockException";
  this.sku = null;
  this.requested = null;
  this.available = null;
  this.message = null;
  if (args) {
    if (args.sku !== undefined && args.sku !== null) {
      this.sku = args.sku;
    }
    if (args.requested !== undefined && args.requested !== null) {
      this.requested = args.requested;
    }
    if (args.available !== undefined && args.available !== null) {
      this.available = args.available;
    }
    if (args.message !== undefined && args.message !== null) {
      this.message = args.message;
    }
  }
};
Thrift.inherits(InsufficientStockException, Thrift.TException);
InsufficientStockException.prototype.name = 'InsufficientStockException';
InsufficientStockException.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.sku = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.requested = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.available = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.message = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InsufficientStockException.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('InsufficientStockException');
  if (this.sku !== null && this.sku !== undefined) {
    output.writeFieldBegin('sku', Thrift.Type.STRING, 1);
    output.writeString(this.sku);
    output.writeFieldEnd();
  }
  if (this.requested !== null && this.requested !== undefined) {
    output.writeFieldBegin('requested', Thrift.Type.I32, 2);
    output.writeI32(this.requested);
    output.writeFieldEnd();
  }
  if (this.available !== null && this.available !== undefined) {
    output.writeFieldBegin('available', Thrift.Type.I32, 3);
    output.writeI32(this.available);
    output.writeFieldEnd();
  }
  if (this.message !== null && this.message !== undefined) {
    output.writeFieldBegin('message', Thrift.Type.STRING, 4);
    output.writeString(this.message);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

